### ISSUE TITLE
Synchronisation Settings not saved

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [cismet/abf#48]
Disabling Synchronisation has no effect. Synchronisation is always re-enabled.

![sync](https://cloud.githubusercontent.com/assets/1788226/9868467/44b5593c-5b79-11e5-8aa4-fdd9bb4584f8.png)

**Comment by mscholl** [comment]
Cannot reproduce. This button (a toggle button) works as expected and indeed has the desired effect (Synchronization of attribute name and field name). Please explain what exactly is the issue here.

**Comment by p-a-s-c-a-l** [comment]
Synchronize **Checkbox**:

[abf](https://cloud.githubusercontent.com/assets/1788226/9880919/10e71ff0-5bce-11e5-9cff-b181ba189720.gif)

**Comment by mscholl** [comment]
What do you expect to happen? Should this setting be persistet in a way that it remains disabled if you reopen the wizard?

**Comment by p-a-s-c-a-l** [comment]
Checkbox = presistent setting. Better use a Button.

**Comment by mscholl** [comment]
@helllth should this be implemented as a new feature? If so should this be persisted to cids DB or to separate properties file or similar?

**Comment by helllth** [comment]
@mscholl no

existing behaviour (check if table_name==class_name  sets the checkbox) is sufficient
