### ISSUE TITLE
Re-index class does not work

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [cismet/abf#52]
Procedures CIDS_REDINDEX_ALL and REINDEX_SINGLE work without problem, but Re-index class in ABF does not.

![re-index](https://cloud.githubusercontent.com/assets/1788226/9954477/a82bd9a6-5de9-11e5-90f3-df71f1f5762a.png)

**Comment by mscholl** [comment]
Depends on cismet/data-objects#30

**Comment by mscholl** [comment]
Solved by data-objects.
