### ISSUE TITLE
Error Adding Configuration Attributes

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [cismet/abf#56]
invokation failed: method=de.cismet.cids.jpa.backend.service.ConfigAttrService.storeEntry | args=[de.cismet.cids.jpa.entity.configattr.ConfigAttrEntry@b9bbcbc] (null) key: [de.cismet.cids.jpa.entity.configattr.ConfigAttrKey@1d83e098] (null) key: csa://borisExportAction, groupName: __no_group__ || value: [de.cismet.cids.jpa.entity.configattr.ConfigAttrValue@3d0e2a4b] (null) value: true

`` org.hibernate.exception.SQLGrammarException: could not execute query       at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:92)       at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)       at org.hibernate.loader.Loader.doList(Loader.java:2452)       at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2192)       at org.hibernate.loader.Loader.list(Loader.java:2187)       at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:452)       at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:363)       at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:196)       at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1258)       at org.hibernate.impl.QueryImpl.list(QueryImpl.java:102)       at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:269)       at de.cismet.cids.jpa.backend.service.impl.ConfigAttrBackend.storeEntry(ConfigAttrBackend.java:277)       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)       at java.lang.reflect.Method.invoke(Method.java:606)       at net.sf.tie.MethodCall.invoke(MethodCall.java:64)       at net.sf.tie.StackInvocation.proceed(StackInvocation.java:99)       at de.cismet.cids.jpa.backend.core.PersistenceInterceptor.invoke(PersistenceInterceptor.java:78)       at net.sf.tie.StackInvocation.proceed(StackInvocation.java:95)       at net.sf.tie.ProxyHandler.invoke(ProxyHandler.java:56)       at com.sun.proxy.$Proxy38.storeEntry(Unknown Source)       at de.cismet.cids.jpa.backend.service.impl.BackendImpl.storeEntry(BackendImpl.java:471)       at de.cismet.cids.abf.domainserver.ReadCacheBackend.storeEntry(ReadCacheBackend.java:173)       at de.cismet.cids.abf.domainserver.project.configattr.ConfigAttrRootNode$NewKeyType$1.run(ConfigAttrRootNode.java:185)       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)       at java.util.concurrent.FutureTask.run(FutureTask.java:262)       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)       at java.lang.Thread.run(Thread.java:745)      Caused by: java.sql.SQLSyntaxErrorException: ORA-00932: inconsistent datatypes: expected - got CLOB             at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:461)       at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:402)       at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1065)       at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:681)       at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:256)       at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:577)       at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:239)       at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:75)       at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:1043)       at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1111)       at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1353)       at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4485)       at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4566)       at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:5251)       at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)       at org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:208)       at org.hibernate.loader.Loader.getResultSet(Loader.java:1869)       at org.hibernate.loader.Loader.doQuery(Loader.java:718)       at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:270)       at org.hibernate.loader.Loader.doList(Loader.java:2449)       ... 27 more ``

**Comment by mscholl** [comment]
the reason for this being cismet/data-objects#32

**Comment by mscholl** [comment]
solved by dataobjects
